//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DOAN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CNPM_DOAN.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài tập.
        /// </summary>
        public static string Bài_tập {
            get {
                return ResourceManager.GetString("Bài tập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG KÝ.
        /// </summary>
        public static string ĐĂNG_KÝ {
            get {
                return ResourceManager.GetString("ĐĂNG KÝ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG NHẬP.
        /// </summary>
        public static string ĐĂNG_NHẬP {
            get {
                return ResourceManager.GetString("ĐĂNG NHẬP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhiệm vụ.
        /// </summary>
        public static string Danh_sách_nhiệm_vụ {
            get {
                return ResourceManager.GetString("Danh sách nhiệm vụ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIỚI THIỆU.
        /// </summary>
        public static string GIỚI_THIỆU {
            get {
                return ResourceManager.GetString("GIỚI THIỆU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIÊN HỆ.
        /// </summary>
        public static string LIÊN_HỆ {
            get {
                return ResourceManager.GetString("LIÊN HỆ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục tiêu.
        /// </summary>
        public static string Mục_tiêu {
            get {
                return ResourceManager.GetString("Mục tiêu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm học tập.
        /// </summary>
        public static string Nhóm_học_tập {
            get {
                return ResourceManager.GetString("Nhóm học tập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu học tập.
        /// </summary>
        public static string Tài_liệu_học_tập {
            get {
                return ResourceManager.GetString("Tài liệu học tập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời khóa biểu.
        /// </summary>
        public static string Thời_khóa_biểu {
            get {
                return ResourceManager.GetString("Thời khóa biểu", resourceCulture);
            }
        }
    }
}
