//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DOAN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CNPM_DOAN.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Quốc Lộ 22, Xã Tân Xuân, Huyện Hóc Môn, thành phố Hồ Chí Mình, Việt Nam.
        /// </summary>
        public static string _10_Quốc_Lộ_22__Xã_Tân_Xuân__Huyện_Hóc_Môn__thành_phố_Hồ_Chí_Mình__Việt_Nam {
            get {
                return ResourceManager.GetString("10 Quốc Lộ 22, Xã Tân Xuân, Huyện Hóc Môn, thành phố Hồ Chí Mình, Việt Nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài tập.
        /// </summary>
        public static string Bài_tập {
            get {
                return ResourceManager.GetString("Bài tập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa tài khoản không?.
        /// </summary>
        public static string Bạn_có_muốn_xóa_tài_khoản_không_ {
            get {
                return ResourceManager.GetString("Bạn có muốn xóa tài khoản không?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các bài tập đã giao.
        /// </summary>
        public static string Các_bài_tập_đã_giao {
            get {
                return ResourceManager.GetString("Các bài tập đã giao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit successfully!.
        /// </summary>
        public static string Cập_nhật_thành_công_ {
            get {
                return ResourceManager.GetString("Cập nhật thành công!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm điểm.
        /// </summary>
        public static string Chấm_điểm {
            get {
                return ResourceManager.GetString("Chấm điểm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm điểm thành công.
        /// </summary>
        public static string Chấm_điểm_thành_công {
            get {
                return ResourceManager.GetString("Chấm điểm thành công", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string Chỉnh_sửa {
            get {
                return ResourceManager.GetString("Chỉnh sửa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa bài nộp.
        /// </summary>
        public static string Chỉnh_sửa_bài_nộp {
            get {
                return ResourceManager.GetString("Chỉnh sửa bài nộp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa nội dung nhiệm vụ.
        /// </summary>
        public static string Chỉnh_sửa_nội_dung_nhiệm_vụ {
            get {
                return ResourceManager.GetString("Chỉnh sửa nội dung nhiệm vụ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa tài liệu.
        /// </summary>
        public static string Chỉnh_sửa_tài_liệu {
            get {
                return ResourceManager.GetString("Chỉnh sửa tài liệu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa tài liệu thành công.
        /// </summary>
        public static string Chỉnh_sửa_tài_liệu_thành_công {
            get {
                return ResourceManager.GetString("Chỉnh sửa tài liệu thành công", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thành công.
        /// </summary>
        public static string Chỉnh_sửa_thành_công {
            get {
                return ResourceManager.GetString("Chỉnh sửa thành công", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thông tin cá nhân.
        /// </summary>
        public static string Chỉnh_sửa_thông_tin_cá_nhân {
            get {
                return ResourceManager.GetString("Chỉnh sửa thông tin cá nhân", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa tiết học.
        /// </summary>
        public static string Chỉnh_sửa_tiết_học {
            get {
                return ResourceManager.GetString("Chỉnh sửa tiết học", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tài liệu.
        /// </summary>
        public static string Chọn_tài_liệu {
            get {
                return ResourceManager.GetString("Chọn tài liệu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có điểm.
        /// </summary>
        public static string Chưa_có_điểm {
            get {
                return ResourceManager.GetString("Chưa có điểm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nộp.
        /// </summary>
        public static string Chưa_nộp {
            get {
                return ResourceManager.GetString("Chưa nộp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Còn hạn.
        /// </summary>
        public static string Còn_hạn {
            get {
                return ResourceManager.GetString("Còn hạn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn thành.
        /// </summary>
        public static string Đã_hoàn_thành {
            get {
                return ResourceManager.GetString("Đã hoàn thành", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nộp.
        /// </summary>
        public static string Đã_nộp {
            get {
                return ResourceManager.GetString("Đã nộp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG KÝ.
        /// </summary>
        public static string ĐĂNG_KÝ {
            get {
                return ResourceManager.GetString("ĐĂNG KÝ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG NHẬP.
        /// </summary>
        public static string ĐĂNG_NHẬP {
            get {
                return ResourceManager.GetString("ĐĂNG NHẬP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Đăng_xuất {
            get {
                return ResourceManager.GetString("Đăng xuất", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhiệm vụ.
        /// </summary>
        public static string Danh_sách_nhiệm_vụ {
            get {
                return ResourceManager.GetString("Danh sách nhiệm vụ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài liệu học tập.
        /// </summary>
        public static string Danh_sách_tài_liệu_học_tập {
            get {
                return ResourceManager.GetString("Danh sách tài liệu học tập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách thời khóa biểu.
        /// </summary>
        public static string Danh_sách_thời_khóa_biểu {
            get {
                return ResourceManager.GetString("Danh sách thời khóa biểu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Địa_chỉ {
            get {
                return ResourceManager.GetString("Địa chỉ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm.
        /// </summary>
        public static string Điểm {
            get {
                return ResourceManager.GetString("Điểm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string Điện_thoại {
            get {
                return ResourceManager.GetString("Điện thoại", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string Đổi_mật_khẩu {
            get {
                return ResourceManager.GetString("Đổi mật khẩu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIA ĐÌNH.
        /// </summary>
        public static string GIA_ĐÌNH {
            get {
                return ResourceManager.GetString("GIA ĐÌNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao nhiệm vụ.
        /// </summary>
        public static string Giao_nhiệm_vụ {
            get {
                return ResourceManager.GetString("Giao nhiệm vụ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIỚI THIỆU.
        /// </summary>
        public static string GIỚI_THIỆU {
            get {
                return ResourceManager.GetString("GIỚI THIỆU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Giới_tính {
            get {
                return ResourceManager.GetString("Giới tính", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Gửi {
            get {
                return ResourceManager.GetString("Gửi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn nộp.
        /// </summary>
        public static string Hạn_nộp {
            get {
                return ResourceManager.GetString("Hạn nộp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy viết mục tiêu của bạn vào đây.
        /// </summary>
        public static string Hãy_viết_mục_tiêu_của_bạn_vào_đây {
            get {
                return ResourceManager.GetString("Hãy viết mục tiêu của bạn vào đây", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy viết nhiệm vụ của bạn vào đây.
        /// </summary>
        public static string Hãy_viết_nhiệm_vụ_của_bạn_vào_đây {
            get {
                return ResourceManager.GetString("Hãy viết nhiệm vụ của bạn vào đây", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống sẽ tự động xóa đi các dữ liệu liên quan đến dữ liệu của bạn và bạn sẽ không thể nào đăng nhập lại bằng tài khoản này được nữa.
        /// </summary>
        public static string Hệ_thống_sẽ_tự_động_xóa_đi_các_dữ_liệu_liên_quan_đến_dữ_liệu_của_bạn_và_bạn_sẽ_không_thể_nào_đăng_nhập_lại_bằng_tài_khoản_này_được_nữa {
            get {
                return ResourceManager.GetString("Hệ thống sẽ tự động xóa đi các dữ liệu liên quan đến dữ liệu của bạn và bạn sẽ kh" +
                        "ông thể nào đăng nhập lại bằng tài khoản này được nữa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hạn.
        /// </summary>
        public static string Hết_hạn {
            get {
                return ResourceManager.GetString("Hết hạn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string Họ_và_tên {
            get {
                return ResourceManager.GetString("Họ và tên", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIÊN HỆ.
        /// </summary>
        public static string LIÊN_HỆ {
            get {
                return ResourceManager.GetString("LIÊN HỆ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi.
        /// </summary>
        public static string Liên_hệ_với_chúng_tôi {
            get {
                return ResourceManager.GetString("Liên hệ với chúng tôi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Lưu {
            get {
                return ResourceManager.GetString("Lưu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Mật_khẩu {
            get {
                return ResourceManager.GetString("Mật khẩu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string Mật_khẩu_cũ {
            get {
                return ResourceManager.GetString("Mật khẩu cũ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string Mật_khẩu_mới {
            get {
                return ResourceManager.GetString("Mật khẩu mới", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục tiêu.
        /// </summary>
        public static string Mục_tiêu {
            get {
                return ResourceManager.GetString("Mục tiêu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu bạn có thắc mắc hoặc cần hỗ trợ hãy liên lạc cho chúng tôi thông qua các cách sau.
        /// </summary>
        public static string Nếu_bạn_có_thắc_mắc_hoặc_cần_hỗ_trợ_hãy_liên_lạc_cho_chúng_tôi_thông_qua_các_cách_sau {
            get {
                return ResourceManager.GetString("Nếu bạn có thắc mắc hoặc cần hỗ trợ hãy liên lạc cho chúng tôi thông qua các cách" +
                        " sau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hoàn thành.
        /// </summary>
        public static string Ngày_hoàn_thành {
            get {
                return ResourceManager.GetString("Ngày hoàn thành", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string Ngày_sinh {
            get {
                return ResourceManager.GetString("Ngày sinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nội dung.
        /// </summary>
        public static string Nhập_nội_dung {
            get {
                return ResourceManager.GetString("Nhập nội dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm học tập.
        /// </summary>
        public static string Nhóm_học_tập {
            get {
                return ResourceManager.GetString("Nhóm học tập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nộp bài.
        /// </summary>
        public static string Nộp_bài {
            get {
                return ResourceManager.GetString("Nộp bài", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nộp bài tập.
        /// </summary>
        public static string Nộp_bài_tập {
            get {
                return ResourceManager.GetString("Nộp bài tập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nộp bài tập thành công!.
        /// </summary>
        public static string Nộp_bài_tập_thành_công_ {
            get {
                return ResourceManager.GetString("Nộp bài tập thành công!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá hạn.
        /// </summary>
        public static string Quá_hạn {
            get {
                return ResourceManager.GetString("Quá hạn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí điểm, bài tập về nhà, giao bài nhanh chóng.
        /// </summary>
        public static string Quản_lí_điểm__bài_tập_về_nhà__giao_bài_nhanh_chóng {
            get {
                return ResourceManager.GetString("Quản lí điểm, bài tập về nhà, giao bài nhanh chóng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí dữ liệu bài tập cho học sinh, an toàn, nhanh chóng.
        /// </summary>
        public static string Quản_lí_dữ_liệu_bài_tập_cho_học_sinh__an_toàn__nhanh_chóng {
            get {
                return ResourceManager.GetString("Quản lí dữ liệu bài tập cho học sinh, an toàn, nhanh chóng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÍ HỌC TẬP TRONG.
        /// </summary>
        public static string QUẢN_LÍ_HỌC_TẬP_TRONG {
            get {
                return ResourceManager.GetString("QUẢN LÍ HỌC TẬP TRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string Quay_lại {
            get {
                return ResourceManager.GetString("Quay lại", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay về trang chủ.
        /// </summary>
        public static string Quay_về_trang_chủ {
            get {
                return ResourceManager.GetString("Quay về trang chủ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu học tập.
        /// </summary>
        public static string Tài_liệu_học_tập {
            get {
                return ResourceManager.GetString("Tài liệu học tập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải xuống.
        /// </summary>
        public static string Tải_xuống {
            get {
                return ResourceManager.GetString("Tải xuống", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo.
        /// </summary>
        public static string Tạo {
            get {
                return ResourceManager.GetString("Tạo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo bài tập mới.
        /// </summary>
        public static string Tạo_bài_tập_mới {
            get {
                return ResourceManager.GetString("Tạo bài tập mới", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo lịch học.
        /// </summary>
        public static string Tạo_lịch_học {
            get {
                return ResourceManager.GetString("Tạo lịch học", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mục tiêu mới thành công.
        /// </summary>
        public static string Tạo_mục_tiêu_mới_thành_công {
            get {
                return ResourceManager.GetString("Tạo mục tiêu mới thành công", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo nhiệm vụ mới thành công.
        /// </summary>
        public static string Tạo_nhiệm_vụ_mới_thành_công {
            get {
                return ResourceManager.GetString("Tạo nhiệm vụ mới thành công", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài liệu thành công.
        /// </summary>
        public static string Tạo_tài_liệu_thành_công {
            get {
                return ResourceManager.GetString("Tạo tài liệu thành công", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create successfully!.
        /// </summary>
        public static string Tạo_thành_công_ {
            get {
                return ResourceManager.GetString("Tạo thành công!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thời khóa biểu mới.
        /// </summary>
        public static string Tạo_thời_khóa_biểu_mới {
            get {
                return ResourceManager.GetString("Tạo thời khóa biểu mới", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tiết học mới.
        /// </summary>
        public static string Tạo_tiết_học_mới {
            get {
                return ResourceManager.GetString("Tạo tiết học mới", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên file.
        /// </summary>
        public static string Tên_file {
            get {
                return ResourceManager.GetString("Tên file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên môn học.
        /// </summary>
        public static string Tên_môn_học {
            get {
                return ResourceManager.GetString("Tên môn học", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string Tên_tài_khoản {
            get {
                return ResourceManager.GetString("Tên tài khoản", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thời khóa biểu.
        /// </summary>
        public static string Tên_thời_khóa_biểu {
            get {
                return ResourceManager.GetString("Tên thời khóa biểu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham gia ngay.
        /// </summary>
        public static string Tham_gia_ngay {
            get {
                return ResourceManager.GetString("Tham gia ngay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm học sinh mới.
        /// </summary>
        public static string Thêm_học_sinh_mới {
            get {
                return ResourceManager.GetString("Thêm học sinh mới", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tài liệu học tập mới.
        /// </summary>
        public static string Thêm_tài_liệu_học_tập_mới {
            get {
                return ResourceManager.GetString("Thêm tài liệu học tập mới", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời khóa biểu.
        /// </summary>
        public static string Thời_khóa_biểu {
            get {
                return ResourceManager.GetString("Thời khóa biểu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê bài tập.
        /// </summary>
        public static string Thống_kê_bài_tập {
            get {
                return ResourceManager.GetString("Thống kê bài tập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ.
        /// </summary>
        public static string Thứ {
            get {
                return ResourceManager.GetString("Thứ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 2.
        /// </summary>
        public static string Thứ_2 {
            get {
                return ResourceManager.GetString("Thứ 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 3.
        /// </summary>
        public static string Thứ_3 {
            get {
                return ResourceManager.GetString("Thứ 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 4.
        /// </summary>
        public static string Thứ_4 {
            get {
                return ResourceManager.GetString("Thứ 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 5.
        /// </summary>
        public static string Thứ_5 {
            get {
                return ResourceManager.GetString("Thứ 5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 6.
        /// </summary>
        public static string Thứ_6 {
            get {
                return ResourceManager.GetString("Thứ 6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 7.
        /// </summary>
        public static string Thứ_7 {
            get {
                return ResourceManager.GetString("Thứ 7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiện lợi, giao diện đơn giản, dễ dàng sử dụng cho học sinh và phụ huynh.
        /// </summary>
        public static string Tiện_lợi__giao_diện_đơn_giản__dễ_dàng_sử_dụng_cho_học_sinh_và_phụ_huynh {
            get {
                return ResourceManager.GetString("Tiện lợi, giao diện đơn giản, dễ dàng sử dụng cho học sinh và phụ huynh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiết bắt đầu.
        /// </summary>
        public static string Tiết_bắt_đầu {
            get {
                return ResourceManager.GetString("Tiết bắt đầu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiết học trùng với tiết học của một môn khác. Vui lòng kiểm tra lại thời khóa biểu của bạn!.
        /// </summary>
        public static string Tiết_học_trùng_với_tiết_học_của_một_môn_khác__Vui_lòng_kiểm_tra_lại_thời_khóa_biểu_của_bạn_ {
            get {
                return ResourceManager.GetString("Tiết học trùng với tiết học của một môn khác. Vui lòng kiểm tra lại thời khóa biể" +
                        "u của bạn!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiết kết thúc.
        /// </summary>
        public static string Tiết_kết_thúc {
            get {
                return ResourceManager.GetString("Tiết kết thúc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiết kết thúc phải lớn hơn hoặc bằng tiết bắt đầu.
        /// </summary>
        public static string Tiết_kết_thúc_phải_lớn_hơn_hoặc_bằng_tiết_bắt_đầu {
            get {
                return ResourceManager.GetString("Tiết kết thúc phải lớn hơn hoặc bằng tiết bắt đầu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôi đã hiểu và muốn tiếp tục.
        /// </summary>
        public static string Tôi_đã_hiểu_và_muốn_tiếp_tục {
            get {
                return ResourceManager.GetString("Tôi đã hiểu và muốn tiếp tục", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string Xác_nhận {
            get {
                return ResourceManager.GetString("Xác nhận", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string Xác_nhận_mật_khẩu {
            get {
                return ResourceManager.GetString("Xác nhận mật khẩu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem bài giải.
        /// </summary>
        public static string Xem_bài_giải {
            get {
                return ResourceManager.GetString("Xem bài giải", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Điểm.
        /// </summary>
        public static string Xem_Điểm {
            get {
                return ResourceManager.GetString("Xem Điểm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Thời khóa biểu.
        /// </summary>
        public static string Xem_Thời_khóa_biểu {
            get {
                return ResourceManager.GetString("Xem Thời khóa biểu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Xóa {
            get {
                return ResourceManager.GetString("Xóa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa mục tiêu thành công.
        /// </summary>
        public static string Xóa_mục_tiêu_thành_công {
            get {
                return ResourceManager.GetString("Xóa mục tiêu thành công", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhiệm vụ thành công.
        /// </summary>
        public static string Xóa_nhiệm_vụ_thành_công {
            get {
                return ResourceManager.GetString("Xóa nhiệm vụ thành công", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tài khoản.
        /// </summary>
        public static string Xóa_tài_khoản {
            get {
                return ResourceManager.GetString("Xóa tài khoản", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tài liệu.
        /// </summary>
        public static string Xóa_tài_liệu {
            get {
                return ResourceManager.GetString("Xóa tài liệu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tài liệu thành công.
        /// </summary>
        public static string Xóa_tài_liệu_thành_công {
            get {
                return ResourceManager.GetString("Xóa tài liệu thành công", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công!.
        /// </summary>
        public static string Xóa_thành_công_ {
            get {
                return ResourceManager.GetString("Xóa thành công!", resourceCulture);
            }
        }
    }
}
