//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAILIEU
    {
        public string IDTaiLieu { get; set; }
        public string TenTaiLieu { get; set; }
        public byte[] TenDuongDan { get; set; }
        public string LoaiTep { get; set; }
        public string IDNguoiTao { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
