//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TODO
    {
        public string IDToDo { get; set; }
        public string NDToDo { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public Nullable<System.DateTime> HanChot { get; set; }
        public string TrangThai { get; set; }
        public string IDNguoiDung { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
